;===============================================================
; Virtuoso Layout Editor Technology File
; for 0.18um Technology Process: 1830AN18BA
;===============================================================
; CHANGE HISTORY
;---------------------------------------------------------------
; Version     Date         Who          Description
; -------     ----------   --------     ------------------------
; preliminary 2009/01/19   B.R.Jung     Initial release
; preliminary 2009/02/03   B.R.Jung     Add LDDBLK(28;0),RESIST(31;0),
;                                           TRENCH(90;0)
; preliminary 2009/05/19   B.R.Jung     Add DUMMETBLK(41;0),ZENER(88;0)
;                                       Delete DNWELL(93;0),NCHSTBLK(30;0)
; preliminary 2009/05/20   B.R.Jung     Add ESDT45(80;0)
; preliminary 2009/07/08   B.R.Jung     Add FG(107;0),CVT(108;0),
;                                           CSD(109;0),FC(110;0)
;                                       Add viaLayers()
; preliminary 2009/07/09   B.R.Jung     Add NSDBLK(116;0),PSDBLK(117;0),
;                                           LVGD(118;)
; preliminary 2009/10/30   B.R.Jung     Add CDM(137;0)
;                                       Delete DIFF text21(3;21)
; preliminary 2009/11/10   B.R.Jung     1824AN18BA techfile unification
; preliminary 2010/02/02   I.H.Na       Change the layer number:
;                                       MTM1(152;0) -> MTM1(147;0)
; v1p0        2010/03/18   I.H.Na       Add layer : ISO_V7(#135), ISO_V30(#136)
;                                                   NSDBLK(#161), PSDBLK(#162)
;             2010/04/19   I.H.Na       Add layer : METTOP(#26)
; r06         2010/11/17   I.H.Na       Add layer : FUSOR(#165), ESDSTK(#166), ESDBOT(#167)
; 1.8.0       2011/01/14   I.H.Na       Add cust1(181:0),cust2(182:0),cust3(183:0),cust4(184:0)
;                                           cust5(185:0)
;                                       Modify "align" Packet (.tf)
;                                       Add CUP_DIA(145:0)
; 1.9.0       2011/02/21   A.R Han      Add LVGD(163:0)
; 2.0.0       2011/06/30   J.Y.Baek     Add LDMTAG(94:0), NDT(100:0), DWELL(102:0), LVNW(140:0)  
;             2011/06/30   J.H.Yoo      Remove  LDMTAG(94:0), NDT(100:0), DWELL(102:0)
;===============================================================

;********************************
; CONTROLS
;********************************
controls(
 techParams(
 ;( parameter           value             )
 ;( ----------          -----             )
  ( maskGrid            0.005 )
  ( cadGrid             0.005 )
  ( drcGrid             0.005 )
  ( mfgGrid             0.005 )
  ( scale               1.0 )
  ( MetalOpt            "1P6M")
  ( MetalType           "Thin")
 ) ;techParams

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( text                      1          txt          )
  ( slot                      2          slt          )
  ( metres3                   3          mr3          )
  ( metres4                   4          mr4          )
  ( metres5                   5          mr5          )
  ( metres6                   6          mr6          )
  ( diff                      7          dif          )
  ( poly                      8          ply          )
  ( metres1                   9          mr1          )
  ( metres2                   10         mr2          )
  ( alll                      11         all          )
  ( met1                      12         me1          )
  ( met2                      13         me2          )
  ( met3                      14         me3          )
  ( met4                      15         me4          )
  ( met5                      16         me5          )
  ( met6                      17         me6          )
  ( drawing63                 63         d63          )
 ;System-Reserved Purposes:
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( drawing                   252        drw          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( PWELL                     1          PWELL        )
  ( NWELL                     2          NWELL        )
  ( DIFF                      3          DIFF         )
  ( POLY                      6          POLY         )
  ( PIMP                      7          PIMP         )
  ( NIMP                      8          NIMP         )
  ( CONT                      9          CONT         )
  ( MET1                      10         MET1         )
  ( VIA1                      11         VIA1         )
  ( MET2                      12         MET2         )
  ( VIA2                      13         VIA2         )
  ( MET3                      14         MET3         )
  ( VIA3                      15         VIA3         )
  ( MET4                      16         MET4         )
  ( VIA4                      17         VIA4         )
  ( MET5                      18         MET5         )
  ( VIA5                      19         VIA5         )
  ( MET6                      20         MET6         )
  ( POR                       21         POR          )
  ( DNW                       22         DNW          )
  ( SDPW                      23         SDPW         )
  ( SDNW                      24         SDNW         )
  ( METTOP                    26         METTOP       )
  ( RESIST                    31         RESIST       )
  ( NWRES                     32         NWRES        )
  ( BTAG                      33         BTAG         )
  ( SDI                       34         SDI          )
  ( METRES                    35         METRES       )
  ( POWPRO                    36         POWPRO       )
  ( HOTNW                     37         HOTNW        )
  ( SEALRING                  38         SEALRIN      )
  ( POLY_CAP                  39         POLY_CA      )
  ( DUMBLK                    40         DUMBLK       )
  ( DUMMETBLK                 41         DUMMETB      )
  ( ARTBOUNDRY                42         ARTBOUN      )
  ( PIP                       43         PIP          )
  ( TXT                       44         TXT          )
  ( MCW                       45         MCW          )
  ( NOGRID                    46         NOGRID       )
  ( SAB                       47         SAB          )
  ( DRCDMY                    48         DRCDMY       )
  ( GR                        49         GR           )
  ( BOND                      50         BOND         )
  ( ANT                       51         ANT          )
  ( ESD                       52         ESD          )
  ( CELLNAME                  53         CELLNAM      )
  ( VARDMY                    54         VARDMY       )
  ( ISPWELL                   55         ISPWELL      )
  ( BOUNDARY                  56         BOUNDAR      )
  ( BLKIO                     57         BLKIO        )
  ( DASDMY                    63         DASDMY       )
  ( SRAM                      64         SRAM         )
  ( ESDMY                     68         ESDMY        )
  ( ESDMY2                    69         ESDMY2       )
  ( DTAG                      70         DTAG         )
  ( DRNTAG                    71         DRNTAG       )
  ( ESDMY1                    76         ESDMY1       )
  ( POLY2                     86         POLY2        )
  ( MTM                       87         MTM          )
  ( FUSE                      88         FUSE         )
  ( HRI                       90         HRI          )
  ( HRID                      91         HRID         )
  ( BLKWELL                   92         BLKWELL      )
  ( STD_B                     95         STD_B        )
  ( PDT                       101        PDT          )
  ( PCHSTBLK                  105        PCHSTBL      )
  ( SDBLK                     107        SDBLK        )
  ( TGOX50                    111        TGOX50       )
  ( V2                        112        V2           )
  ( V5                        114        V5           )
  ( V7                        115        V7           )
  ( V12                       116        V12          )
  ( V20                       117        V20          )
  ( V30                       118        V30          )
  ( ESDT45                    131        ESDT45       )
  ( ISO_V7                    135        ISO_V7       )
  ( ISO_V30                   136        ISO_V30      )
  ( CDM                       137        CDM          )
  ( LVNW                      140        LVNW         )
  ( FG                        141        FG           )
  ( CVT                       142        CVT          )
  ( CSD                       143        CSD          )
  ( FC                        144        FC           )
  ( CUP_DIA                   145        CUP_DIA      )
  ( MTM1                      147        MTM1         )
  ( ZENER                     148        ZENER        )
  ( EEPROM                    149        EEPROM       )
  ( EPROM                     150        EPROM        )
  ( ANLGDMY                   154        ANLGDMY      )
  ( LDDBLK                    155        LDDBLK       )
  ( NSDBLK                    161        NSDBLK       )
  ( PSDBLK                    162        PSDBLK       )
  ( LVGD                      163        LVGD         )
  ( FUSOR                     165        FUSOR        )
  ( ESDSTK                    166        ESDSTK       )
  ( ESDBOT                    167        ESDBOT       )
  ( cust1                     181        cust1        )
  ( cust2                     182        cust2        )
  ( cust3                     183        cust3        )
  ( cust4                     184        cust4        )
  ( cust5                     185        cust5        )
  ( OVERLAP                   190        OVERLAP      )
  ( DBL                       191        DBL          )

 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( PWELL                     drawing    )
  ( PWELL                     text       )
  ( NWELL                     drawing    )
  ( NWELL                     text       )
  ( DIFF                      drawing    )
  ( DIFF                      text       )
  ( POLY                      drawing    )
  ( POLY                      text       )
  ( PIMP                      drawing    )
  ( NIMP                      drawing    )
  ( CONT                      drawing    )
  ( MET1                      drawing    )
  ( MET1                      text       )
  ( MET1                      slot       )
  ( VIA1                      drawing    )
  ( MET2                      drawing    )
  ( MET2                      text       )
  ( MET2                      slot       )
  ( VIA2                      drawing    )
  ( MET3                      drawing    )
  ( MET3                      text       )
  ( MET3                      slot       )
  ( VIA3                      drawing    )
  ( MET4                      drawing    )
  ( MET4                      text       )
  ( MET4                      slot       )
  ( VIA4                      drawing    )
  ( MET5                      drawing    )
  ( MET5                      text       )
  ( MET5                      slot       )
  ( VIA5                      drawing    )
  ( MET6                      drawing    )
  ( MET6                      text       )
  ( MET6                      slot       )
  ( POR                       drawing    )
  ( DNW                       drawing    )
  ( SDPW                      drawing    )
  ( SDNW                      drawing    )
  ( METTOP                    drawing    )
  ( RESIST                    drawing    )
  ( NWRES                     drawing    )
  ( BTAG                      drawing    )
  ( SDI                       drawing    )
  ( METRES                    metres1    )
  ( METRES                    metres2    )
  ( METRES                    metres3    )
  ( METRES                    metres4    )
  ( METRES                    metres5    )
  ( METRES                    metres6    )
  ( POWPRO                    drawing    )
  ( HOTNW                     drawing    )
  ( SEALRING                  drawing    )
  ( POLY_CAP                  drawing    )
  ( DUMBLK                    alll       )
  ( DUMBLK                    met1       )
  ( DUMBLK                    met2       )
  ( DUMBLK                    met3       )
  ( DUMBLK                    met4       )
  ( DUMBLK                    met5       )
  ( DUMBLK                    met6       )
  ( DUMBLK                    diff       )
  ( DUMBLK                    poly       )
  ( DUMMETBLK                 drawing    )
  ( ARTBOUNDRY                drawing    )
  ( PIP                       drawing    )
  ( TXT                       text       )
  ( MCW                       drawing    )
  ( NOGRID                    drawing    )
  ( SAB                       drawing    )
  ( DRCDMY                    drawing    )
  ( GR                        drawing    )
  ( BOND                      drawing    )
  ( ANT                       drawing    )
  ( ESD                       drawing    )
  ( CELLNAME                  text       )
  ( VARDMY                    drawing    )
  ( ISPWELL                   drawing    )
  ( BOUNDARY                  drawing    )
  ( BLKIO                     drawing    )
  ( DASDMY                    drawing63  )
  ( SRAM                      drawing    )
  ( ESDMY                     drawing    )
  ( ESDMY2                    drawing    )
  ( DTAG                      drawing    )
  ( DRNTAG                    drawing    )
  ( ESDMY1                    drawing    )
  ( POLY2                     drawing    )
  ( MTM                       drawing    )
  ( FUSE                      drawing    )
  ( HRI                       drawing    )
  ( HRID                      drawing    )
  ( BLKWELL                   drawing    )
  ( STD_B                     drawing    )
  ( PDT                       drawing    )
  ( PCHSTBLK                  drawing    )
  ( SDBLK                     drawing    )
  ( TGOX50                    drawing    )
  ( V2                        drawing    )
  ( V5                        drawing    )
  ( V7                        drawing    )
  ( V12                       drawing    )
  ( V20                       drawing    )
  ( V30                       drawing    )
  ( ESDT45                    drawing    )
  ( ISO_V7                    drawing    )
  ( ISO_V30                   drawing    )
  ( CDM                       drawing    )
  ( LVNW                      drawing    )
  ( FG                        drawing    )
  ( CVT                       drawing    )
  ( CSD                       drawing    )
  ( FC                        drawing    )
  ( CUP_DIA                   drawing    )
  ( ZENER                     drawing    )
  ( EEPROM                    drawing    )
  ( EPROM                     drawing    )
  ( MTM1                      drawing    )
  ( ANLGDMY                   drawing    )
  ( LDDBLK                    drawing    )
  ( NSDBLK                    drawing    )
  ( PSDBLK                    drawing    )
  ( LVGD                      drawing    )
  ( FUSOR                     drawing    )
  ( ESDSTK                    drawing    )
  ( ESDBOT                    drawing    )
  ( cust1                     drawing    )
  ( cust2                     drawing    )
  ( cust3                     drawing    )
  ( cust4                     drawing    )
  ( cust5                     drawing    )
  ( OVERLAP                   boundary   )
  ( DBL                       drawing    )
  ( PWELL                     net    )
  ( NWELL                     net    )
  ( DIFF                      net    )
  ( POLY                      net    )
  ( PIMP                      net    )
  ( NIMP                      net    )
  ( CONT                      net    )
  ( MET1                      net    )
  ( VIA1                      net    )
  ( MET2                      net    )
  ( VIA2                      net    )
  ( MET3                      net    )
  ( VIA3                      net    )
  ( MET4                      net    )
  ( VIA4                      net    )
  ( MET5                      net    )
  ( VIA5                      net    )
  ( MET6                      net    )
  ( POR                       net    )
  ( DNW                       net    )
  ( SDPW                      net    )
  ( SDNW                      net    )
  ( METTOP                    net    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      boundary   )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( PWELL        drawing      PWELL            t t t t nil )
  ( PWELL        text         PWTXT            t t t t nil )
  ( NWELL        drawing      NWELL            t t t t nil )
  ( NWELL        text         NWTXT            t t t t nil )
  ( DIFF         drawing      DIFF             t t t t t )
  ( DIFF         text         DIFFTXT          t t t t t )
  ( POLY         drawing      POLY             t t t t t )
  ( POLY         text         POLYTXT          t t t t t )
  ( PIMP         drawing      PIMP             t t t t t )
  ( NIMP         drawing      NIMP             t t t t t )
  ( CONT         drawing      CONT             t t t t t )
  ( MET1         drawing      MET1             t t t t t )
  ( MET1         text         MET1TXT          t t t t t )
  ( MET1         slot         MET1SLT          t t t t t )
  ( VIA1         drawing      VIA1             t t t t t )
  ( MET2         drawing      MET2             t t t t t )
  ( MET2         text         MET2TXT          t t t t t )
  ( MET2         slot         MET2SLT          t t t t t )
  ( VIA2         drawing      VIA2             t t t t t )
  ( MET3         drawing      MET3             t t t t t )
  ( MET3         text         MET3TXT          t t t t t )
  ( MET3         slot         MET3SLT          t t t t t )
  ( VIA3         drawing      VIA3             t t t t t )
  ( MET4         drawing      MET4             t t t t t )
  ( MET4         text         MET4TXT          t t t t t )
  ( MET4         slot         MET4SLT          t t t t t )
  ( VIA4         drawing      VIA4             t t t t t )
  ( MET5         drawing      MET5             t t t t t )
  ( MET5         text         MET5TXT          t t t t t )
  ( MET5         slot         MET5SLT          t t t t t )
  ( VIA5         drawing      VIA5             t t t t t )
  ( MET6         drawing      MET6             t t t t t )
  ( MET6         text         MET6TXT          t t t t t )
  ( MET6         slot         MET6SLT          t t t t t )
  ( POR          drawing      POR              t t t t t )
  ( DNW          drawing      DNW              t t t t t )
  ( SDPW         drawing      SDPW             t t t t t )
  ( SDNW         drawing      SDNW             t t t t t )
  ( METTOP       drawing      METTOP           t t t t t )
  ( RESIST       drawing      RESIST           t t t t t )
  ( NWRES        drawing      NWRES            t t t t t )
  ( BTAG         drawing      BTAG             t t t t t )
  ( SDI          drawing      SDI              t t t t t )
  ( METRES       metres1      METRES1          t t t t t )
  ( METRES       metres2      METRES2          t t t t t )
  ( METRES       metres3      METRES3          t t t t t )
  ( METRES       metres4      METRES4          t t t t t )
  ( METRES       metres5      METRES5          t t t t t )
  ( METRES       metres6      METRES6          t t t t t )
  ( POWPRO       drawing      POWPRO           t t t t t )
  ( HOTNW        drawing      HOTNW            t t t t t )
  ( SEALRING     drawing      SEALRING         t t t t t )
  ( POLY_CAP     drawing      POLY_CAP         t t t t t )
  ( DUMBLK       alll         DUMBLKALL        t t t t t )
  ( DUMBLK       met1         DUMBLKM1         t t t t t )
  ( DUMBLK       met2         DUMBLKM2         t t t t t )
  ( DUMBLK       met3         DUMBLKM3         t t t t t )
  ( DUMBLK       met4         DUMBLKM4         t t t t t )
  ( DUMBLK       met5         DUMBLKM5         t t t t t )
  ( DUMBLK       met6         DUMBLKM6         t t t t t )
  ( DUMBLK       diff         DUMBLKDF         t t t t t )
  ( DUMBLK       poly         DUMBLKPY         t t t t t )
  ( DUMMETBLK    drawing      DUMMETBLK        t t t t t )
  ( ARTBOUNDRY   drawing      ARTBOUNDRY       t t t t t )
  ( PIP          drawing      PIP              t t t t t )
  ( TXT          text         TXT              t t t t t )
  ( MCW          drawing      MCW              t t t t t )
  ( NOGRID       drawing      NOGRID           t t t t t )
  ( SAB          drawing      SAB              t t t t t )
  ( DRCDMY       drawing      DRCDMY           t t t t t )
  ( GR           drawing      GR               t t t t t )
  ( BOND         drawing      BOND             t t t t t )
  ( ANT          drawing      ANT              t t t t t )
  ( ESD          drawing      ESD              t t t t t )
  ( CELLNAME     text         CELLNAME         t t t t t )
  ( VARDMY       drawing      VARDMY           t t t t t )
  ( ISPWELL      drawing      ISPWELL          t t t t t )
  ( BOUNDARY     drawing      BOUNDARY         t t t t t )
  ( BLKIO        drawing      BLKIO            t t t t t )
  ( DASDMY       drawing63    DASDMY           t t t t t )
  ( SRAM         drawing      SRAM             t t t t t )
  ( ESDMY        drawing      ESDMY            t t t t t )
  ( ESDMY2       drawing      ESDMY2           t t t t t )
  ( DTAG         drawing      DTAG             t t t t t )
  ( DRNTAG       drawing      DRNTAG           t t t t t )
  ( ESDMY1       drawing      ESDMY1           t t t t t )
  ( POLY2        drawing      POLY2            t t t t t )
  ( MTM          drawing      MTM              t t t t t )
  ( FUSE         drawing      FUSE             t t t t t )
  ( HRI          drawing      HRI              t t t t t )
  ( HRID         drawing      HRID             t t t t t )
  ( BLKWELL      drawing      BLKWELL          t t t t t )
  ( STD_B        drawing      STD_B            t t t t t )
  ( PDT          drawing      PDT              t t t t t )
  ( PCHSTBLK     drawing      PCHSTBLK         t t t t t )
  ( SDBLK        drawing      SDBLK            t t t t t )
  ( TGOX50       drawing      TGOX50           t t t t t )
  ( V2           drawing      V2               t t t t nil )
  ( V5           drawing      V5               t t t t t )
  ( V7           drawing      V7               t t t t t )
  ( V12          drawing      V12              t t t t t )
  ( V20          drawing      V20              t t t t t )
  ( V30          drawing      V30              t t t t t )
  ( ESDT45       drawing      ESDT45           t t t t t )
  ( ISO_V7       drawing      ISO_V7           t t t t t )
  ( ISO_V30      drawing      ISO_V30          t t t t t )
  ( CDM          drawing      CDM              t t t t t )
  ( LVNW         drawing      LVNW             t t t t t )
  ( FG           drawing      FG               t t t t t )
  ( CVT          drawing      CVT              t t t t t )
  ( CSD          drawing      CSD              t t t t t )
  ( FC           drawing      FC               t t t t t )
  ( CUP_DIA      drawing      CUP_DIA          t t t t t )
  ( ZENER        drawing      ZENER            t t t t t )
  ( EEPROM       drawing      EEPROM           t t t t t )
  ( EPROM        drawing      EPROM            t t t t t )
  ( MTM1         drawing      MTM1             t t t t t )
  ( ANLGDMY      drawing      ANLGDMY          t t t t t )
  ( LDDBLK       drawing      LDDBLK           t t t t t )
  ( NSDBLK       drawing      NSDBLK           t t t t t )
  ( PSDBLK       drawing      PSDBLK           t t t t t )
  ( LVGD         drawing      LVGD             t t t t t )
  ( FUSOR        drawing      FUSOR            t t t t t )
  ( ESDSTK       drawing      ESDSTK           t t t t t )
  ( ESDBOT       drawing      ESDBOT           t t t t t )
  ( cust1        drawing      cust1            t t t t t )
  ( cust2        drawing      cust2            t t t t t )
  ( cust3        drawing      cust3            t t t t t )
  ( cust4        drawing      cust4            t t t t t )
  ( cust5        drawing      cust5            t t t t t )
  ( OVERLAP      boundary     OVERLAP          t t t t t )
  ( DBL          drawing      DBL              t t t t t )
  ( PWELL        net      PWELL            t t t t nil )
  ( NWELL        net      NWELL            t t t t nil )
  ( DIFF         net      DIFF             t t t t t )
  ( POLY         net      POLY             t t t t t )
  ( PIMP         net      PIMP             t t t t t )
  ( NIMP         net      NIMP             t t t t t )
  ( CONT         net      CONT             t t t t t )
  ( MET1         net      MET1             t t t t t )
  ( VIA1         net      VIA1             t t t t t )
  ( MET2         net      MET2             t t t t t )
  ( VIA2         net      VIA2             t t t t t )
  ( MET3         net      MET3             t t t t t )
  ( VIA3         net      VIA3             t t t t t )
  ( MET4         net      MET4             t t t t t )
  ( VIA4         net      VIA4             t t t t t )
  ( MET5         net      MET5             t t t t t )
  ( VIA5         net      VIA5             t t t t t )
  ( MET6         net      MET6             t t t t t )
  ( POR          net      POR              t t t t t )
  ( DNW          net      DNW              t t t t t )
  ( SDPW         net      SDPW             t t t t t )
  ( SDNW         net      SDNW             t t t t t )
  ( METTOP       net      METTOP           t t t t t )
  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      align            t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( text         drawing      text             t t t t nil )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         boundary     snap             t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t nil nil nil nil )
  ( designFlow   drawing1     designFlow1      t nil nil nil nil )
  ( designFlow   drawing2     designFlow2      t nil nil nil nil )
  ( designFlow   drawing3     designFlow3      t nil nil nil nil )
  ( designFlow   drawing4     designFlow4      t nil nil nil nil )
  ( designFlow   drawing5     designFlow5      t nil nil nil nil )
  ( designFlow   drawing6     designFlow6      t nil nil nil nil )
  ( designFlow   drawing7     designFlow7      t nil nil nil nil )
  ( designFlow   drawing8     designFlow8      t nil nil nil nil )
  ( designFlow   drawing9     designFlow9      t nil nil nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
 ) ;techDisplays

techLayerProperties(
;( PropName               Layer1 [ Layer2 ]            PropValue )
 ( iccMaskNumber          (NWELL             drawing )   0 )
 ( iccMaskNumber          (PWELL             drawing )   0 )
 ( iccMaskNumber          (POLY              drawing )   0 )
 ( iccMaskNumber          (NIMP              drawing )   0 )
 ( iccMaskNumber          (PIMP              drawing )   0 )
 ( iccMaskNumber          (CONT              drawing )   0 )
 ( iccMaskNumber          (MET1              drawing )   0 )
 ( iccMaskNumber          (VIA1              drawing )   0 )
 ( iccMaskNumber          (MET2              drawing )   0 )
 ( iccMaskNumber          (VIA2              drawing )   0 )
 ( iccMaskNumber          (MET3              drawing )   0 )
 ( iccMaskNumber          (VIA3              drawing )   0 )
 ( iccMaskNumber          (MET4              drawing )   0 )
 ( iccMaskNumber          (VIA4              drawing )   0 )
 ( iccMaskNumber          (MET5              drawing )   0 )
 ( iccMaskNumber          (VIA5              drawing )   0 )
 ( iccMaskNumber          (MET6              drawing )   0 )
)

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 streamLayers(
 ;( layer       streamNumber    dataType        translate )
 ;( -----       ------------    --------        --------- )
 ;( ("PWELL" "drawing") 1           0         t  )
 ;( ("PWELL" "text")  1           1         t  )
 ;( ("NWELL" "drawing") 2           0         t  )
 ;( ("NWELL" "text")  2           1         t  )
  ( ("DIFF" "drawing")  3           0         t  )
  ( ("DIFF" "text") 3           1         t  )
  ( ("POLY" "drawing")  6           0         t  )
  ( ("POLY" "text") 6           1         t  )
  ( ("PIMP" "drawing")  7           0         t  )
  ( ("NIMP" "drawing")  8           0         t  )
  ( ("CONT" "drawing")  9           0         t  )
  ( ("MET1" "drawing")  10          0         t  )
  ( ("MET1" "text") 10          1         t  )
  ( ("MET1" "slot") 10          2         t  )
  ( ("VIA1" "drawing")  11          0         t  )
  ( ("MET2" "drawing")  12          0         t  )
  ( ("MET2" "text") 12          1         t  )
  ( ("MET2" "slot") 12          2         t  )
  ( ("VIA2" "drawing")  13          0         t  )
  ( ("MET3" "drawing")  14          0         t  )
  ( ("MET3" "text") 14          1         t  )
  ( ("MET3" "slot") 14          2         t  )
  ( ("VIA3" "drawing")  15          0         t  )
  ( ("MET4" "drawing")  16          0         t  )
  ( ("MET4" "text") 16          1         t  )
  ( ("MET4" "slot") 16          2         t  )
  ( ("VIA4" "drawing")  17          0         t  )
  ( ("MET5" "drawing")  18          0         t  )
  ( ("MET5" "text") 18          1         t  )
  ( ("MET5" "slot") 18          2         t  )
  ( ("VIA5" "drawing")  19          0         t  )
  ( ("MET6" "drawing")  20          0         t  )
  ( ("MET6" "text") 20          1         t  )
  ( ("MET6" "slot") 20          2         t  )
  ( ("POR" "drawing") 21          0         t  )
  ( ("DNW" "drawing") 22          0         t  )
  ( ("SDPW" "drawing")  23          0         t  )
  ( ("SDNW" "drawing")  24          0         t  )
  ( ("METTOP" "drawing")  26          0         t  )
  ( ("RESIST" "drawing")  31          0         t  )
  ( ("NWRES" "drawing") 32          0         t  )
  ( ("BTAG" "drawing")  33          0         t  )
  ( ("SDI" "drawing") 34          0         t  )
  ( ("METRES" "metres1")  35          1         t  )
  ( ("METRES" "metres2")  35          2         t  )
  ( ("METRES" "metres3")  35          3         t  )
  ( ("METRES" "metres4")  35          4         t  )
  ( ("METRES" "metres5")  35          5         t  )
  ( ("METRES" "metres6")  35          6         t  )
  ( ("POWPRO" "drawing")  36          0         t  )
  ( ("HOTNW" "drawing") 37          0         t  )
  ( ("SEALRING" "drawing")  38          0         t  )
  ( ("POLY_CAP" "drawing")  39          0         t  )
  ( ("DUMBLK" "alll") 40          0         t  )
  ( ("DUMBLK" "met1") 40          1         t  )
  ( ("DUMBLK" "met2") 40          2         t  )
  ( ("DUMBLK" "met3") 40          3         t  )
  ( ("DUMBLK" "met4") 40          4         t  )
  ( ("DUMBLK" "met5") 40          5         t  )
  ( ("DUMBLK" "met6") 40          6         t  )
  ( ("DUMBLK" "diff") 40          7         t  )
  ( ("DUMBLK" "poly") 40          8         t  )
  ( ("DUMMETBLK" "drawing") 41          0         t  )
  ( ("ARTBOUNDRY" "drawing")  42          0         t  )
  ( ("PIP" "drawing") 43          0         t  )
  ( ("TXT" "text")  44          0         t  )
  ( ("MCW" "drawing") 45          0         t  )
  ( ("NOGRID" "drawing")  46          0         t  )
  ( ("SAB" "drawing") 47          0         t  )
  ( ("DRCDMY" "drawing")  48          0         t  )
  ( ("GR" "drawing")  49          0         t  )
  ( ("BOND" "drawing")  50          0         t  )
  ( ("ANT" "drawing") 51          0         t  )
  ( ("ESD" "drawing") 52          0         t  )
  ( ("CELLNAME" "text") 53          0         t  )
  ( ("VARDMY" "drawing")  54          0         t  )
  ( ("ISPWELL" "drawing") 55          0         t  )
  ( ("BOUNDARY" "drawing")  56          0         t  )
  ( ("BLKIO" "drawing") 57          0         t  )
  ( ("DASDMY" "drawing63")  63          63        t  )
  ( ("SRAM" "drawing")  64          0         t  )
  ( ("ESDMY" "drawing") 68          0         t  )
  ( ("ESDMY2" "drawing")  69          0         t  )
  ( ("DTAG" "drawing")  70          0         t  )
  ( ("DRNTAG" "drawing")  71          0         t  )
  ( ("ESDMY1" "drawing")  76          0         t  )
  ( ("POLY2" "drawing") 86          0         t  )
  ( ("MTM" "drawing") 87          0         t  )
  ( ("FUSE" "drawing")  88          0         t  )
  ( ("HRI" "drawing") 90          0         t  )
  ( ("HRID" "drawing")  91          0         t  )
  ( ("BLKWELL" "drawing") 92          0         t  )
  ( ("STD_B" "drawing") 95          0         t  )
  ( ("PDT" "drawing") 101         0         t  )
  ( ("PCHSTBLK" "drawing")  105         0         t  )
  ( ("SDBLK" "drawing") 107         0         t  )
  ( ("TGOX50" "drawing")  111         0         t  )
  ;( ("V2" "drawing")  112         0         t  )
  ( ("V5" "drawing")  114         0         t  )
  ( ("V7" "drawing")  115         0         t  )
  ( ("V12" "drawing") 116         0         t  )
  ( ("V20" "drawing") 117         0         t  )
  ( ("V30" "drawing") 118         0         t  )
  ( ("ESDT45" "drawing")  131         0         t  )
  ( ("ISO_V7" "drawing")	135       	0       	t	 )
  ( ("ISO_V30" "drawing")	136       	0       	t	 )
  ( ("CDM" "drawing") 137         0         t  )
  ( ("LVNW" "drawing")	140       	0       	t	 )
  ( ("FG" "drawing")  141         0         t  )
  ( ("CVT" "drawing") 142         0         t  )
  ( ("CSD" "drawing") 143         0         t  )
  ( ("FC" "drawing")  144         0         t  )
  ( ("CUP_DIA" "drawing")	145       	0       	t	 )
  ( ("MTM1" "drawing")  147         0         t  )
  ( ("ZENER" "drawing") 148         0         t  )
  ( ("EEPROM" "drawing")  149         0         t  )
  ( ("EPROM" "drawing") 150         0         t  )
  ( ("ANLGDMY" "drawing") 154         0         t  )
  ( ("LDDBLK" "drawing")  155         0         t  )
  ( ("NSDBLK" "drawing")  161         0         t  )
  ( ("PSDBLK" "drawing")  162         0         t  )
  ( ("LVGD" "drawing")  163             0               t        )
  ( ("FUSOR" "drawing")  165         0         t  )
  ( ("ESDSTK" "drawing")  166         0         t  )
  ( ("ESDBOT" "drawing")  167         0         t  )
  ( ("cust1" "drawing")         181             0               t        )
  ( ("cust2" "drawing")         182             0               t        )
  ( ("cust3" "drawing")         183             0               t        )
  ( ("cust4" "drawing")         184             0               t        )
  ( ("cust5" "drawing")         185             0               t        )
  ( ("OVERLAP" "boundary")  190         0         t  )
  ( ("DBL" "drawing") 191         0         t  )
 ) ;streamLayers

 viaLayers(
 ;( layer1      viaLayer        layer2     )
 ;( ------      --------        ------     )
  ( POLY        CONT            MET1         )
  ( MET1        VIA1            MET2         )
  ( MET2        VIA2            MET3         )
  ( MET3        VIA3            MET4         )
  ( MET4        VIA4            MET5         )
  ( MET5        VIA5            MET6         )
 ) ;viaLayers

 layerFunctions(
;  ( layer              function )
;  ( -----              -------- )
   ( NWELL              "nwell"  )
   ( PWELL              "pwell"  )
   ( PIMP               "pdiff"  )
   ( NIMP               "ndiff"  )
   ( POLY               "poly"   )
   ( CONT               "cut"    )
   ( MET1               "metal"  )
   ( VIA1               "cut"    )
   ( MET2               "metal"  )
   ( VIA2               "cut"    )
   ( MET3               "metal"  )
   ( VIA3               "cut"    )
   ( MET4               "metal"  )
   ( VIA4               "cut"    )
   ( MET5               "metal"  )
   ( VIA5               "cut"    )
   ( MET6               "metal"  )

 ) ; layerFunctions


) ;layerRules


;********************************
; PHYSICAL RULES
;********************************
physicalRules(

 spacingRules(
  ;( rule               layer1          layer2          value    )
  ;( ----               ------          ------          -----    )
   ( minWidth           "SDNW"                          0.86     )
   ( minNotch           "SDNW"                          0.6      )
   ( minSpacing         "SDNW"                          1.40     )
   ( minWidth           "DNW"                           3.0      )
   ( minNotch           "DNW"                           5.0      )
   ( minSpacing         "DNW"                           5.0      )
   ( minWidth           "SDPW"                          0.86     )
   ( minNotch           "SDPW"                          0.60     )
   ( minSpacing         "SDPW"                          1.40     )
   ( minWidth           "NWELL"                         0.86     )
   ( minNotch           "NWELL"                         0.6      )
   ( minSpacing         "NWELL"                         1.4      )
   ( minWidth           "PWELL"                         0.86     )
   ( minNotch           "PWELL"                         0.6      )
   ( minSpacing         "PWELL"                         1.4      )
   ( minWidth           "DIFF"                          0.22     ) 
   ( minSpacing         "DIFF"                          0.28     ) 
   ( minArea            "DIFF"                          0.2025   ) 
   ( minWidth           "POLY"                          0.18     ) 
   ( minSpacing         "POLY"                          0.25     ) 
   ( minExtension       "POLY"                          0.22     ) 
   ( minWidth           "NIMP"                          0.44     ) 
   ( minSpacing         "NIMP"                          0.44     ) 
   ( minArea            "NIMP"                          0.3844   ) 
   ( minWidth           "PIMP"                          0.44     ) 
   ( minSpacing         "PIMP"                          0.44     ) 
   ( minArea            "PIMP"                          0.3844   ) 
   ( minWidth           "CONT"                          0.22     ) 
   ( minSpacing         "CONT"                          0.28     ) 
   ( minWidth           "MET1"                          0.23     ) 
   ( minSpacing         "MET1"                          0.23     ) 
   ( minArea            "MET1"                          0.2025   ) 
   ( minWidth           "VIA1"                          0.26     ) 
   ( minSpacing         "VIA1"                          0.26     ) 
   ( minWidth           "MET2"                          0.28     ) 
   ( minSpacing         "MET2"                          0.28     ) 
   ( minArea            "MET2"                          0.2025   ) 
   ( minWidth           "VIA2"                          0.26     ) 
   ( minSpacing         "VIA2"                          0.26     ) 
   ( minWidth           "MET3"                          0.28     ) 
   ( minSpacing         "MET3"                          0.28     ) 
   ( minArea            "MET3"                          0.2025   ) 
   ( minWidth           "VIA3"                          0.26     ) 
   ( minSpacing         "VIA3"                          0.26     ) 
   ( minWidth           "MET4"                          0.28     ) 
   ( minSpacing         "MET4"                          0.28     ) 
   ( minArea            "MET4"                          0.2025   ) 
   ( minWidth           "VIA4"                          0.26     ) 
   ( minSpacing         "VIA4"                          0.26     ) 
   ( minWidth           "MET5"                          0.28     ) 
   ( minSpacing         "MET5"                          0.28     ) 
   ( minArea            "MET5"                          0.2025   ) 
   ( minWidth           "VIA5"                          0.36     ) 
   ( minSpacing         "VIA5"                          0.35     ) 
   ( minWidth           "MET6"                          0.44     ) 
   ( minSpacing         "MET6"                          0.46     )  
   ( minArea            "MET6"                          0.5625   )  
   ( minSpacing         "DNW"           "NWELL"         3.50     )
   ( minSpacing         "SDNW"          "NWELL"         4.90     )
   ( minSpacing         "SDNW"          "PWELL"         2.0      )
   ( minSpacing         "SDPW"          "NWELL"         2.0      )
   ( minSpacing         "SDPW"          "PWELL"         3.4      )
   ( minSpacing         "SDPW"          "SDNW"          0.0      )
   ( minSpacing         "DIFF"          "POLY"          0.1      )
   ( minSpacing         "DIFF"          "CONT"          0.1      )
   ( minSpacing         "POLY"          "CONT"          0.16     )

  ) ; spacingRules

  orderedSpacingRules(
  ;( rule               layer1          layer2          value    )
  ;( ----               ------          ------          -----    )
   ( minEnclosure       "DNW"           "NWELL"         1.5      )
   ( minEnclosure       "DIFF"          "CONT"          0.1      )
   ( minEnclosure       "POLY"          "CONT"          0.1      )
   ( minEnclosure       "MET1"          "CONT"          0.06    )
   ( minEnclosure       "MET1"          "VIA1"          0.06     )
   ( minEnclosure       "MET2"          "VIA1"          0.06     ) ; 21E20b
   ( minEnclosure       "MET2"          "VIA2"          0.06     ) ; 22E21b
   ( minEnclosure       "MET3"          "VIA2"          0.06     ) ; 23E22b
   ( minEnclosure       "MET3"          "VIA3"          0.06     ) ; 24E23b
   ( minEnclosure       "MET4"          "VIA3"          0.06     ) ; 25E24b
   ( minEnclosure       "MET4"          "VIA4"          0.06     ) ; 26E25b
   ( minEnclosure       "MET5"          "VIA4"          0.06     ) ; 27E26b
   ( minEnclosure       "MET5"          "VIA5"          0.06     ) ; 28E27b
   ( minEnclosure       "MET6"          "VIA5"          0.09     ) ; 29E28a

 ) ; orderedSpacingRules

 mfgGridResolution(
      ( 0.005000 )
 ) ;mfgGridResolution

) ;physicalRules


;********************************
; DEVICES
;********************************
devices(
   tcCreateCDSDeviceClass()

;
; no syEnhancement devices
;

;
; no syDepletion devices
;

 symContactDevice(
;     (name viaLayer viaPurpose layer1 purpose1 layer2 purpose2
;      w l (row column xPitch yPitch xBias yBias) encByLayer1 encByLayer2 legalRegion)
   (M1_PDIFF CONT drawing DIFF drawing (PIMP drawing 0.02) MET1 drawing
   0.22 0.22 (1 1 0.47 0.47 center center) 0.1 0.06 _NA_)

   (M1_NDIFF CONT drawing DIFF drawing (NIMP drawing 0.02) MET1 drawing
   0.22 0.22 (1 1 0.47 0.47 center center) 0.1 0.06 _NA_)
 ) ; symContactDevice

  cdsViaDevice(
; (name cutLayer cutPurpose layer1 purpose1 layer2 purpose2
;  row column origin stackedVias cutLayerW cutLayerL xCutSpacing yCutSpacing
;  layer1XEnc layer1YEnc layer2XEnc layer2YEnc layer1Dir layer2Dir)

   (M1_POLYc CONT drawing POLY drawing MET1 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "Y" "X")

   (M1_DIFFc CONT drawing DIFF drawing MET1 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "Y" "X")

   (M2_M1c VIA1 drawing MET1 drawing MET2 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "X" "Y")

   (M3_M2c VIA2 drawing MET2 drawing MET3 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "Y" "X")

   (M4_M3c VIA3 drawing MET3 drawing MET4 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "X" "Y")

   (M5_M4c VIA4 drawing MET4 drawing MET5 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "Y" "X")

   (M6_M5c VIA5 drawing MET5 drawing MET6 drawing
   1 1 centerCenter t _def_ _def_ _def_ _def_
   _def_ _def_ _def_ _def_ "X" "Y")

  ) ; cdsViaDevice

 tfcDefineDeviceProp(
 ;(viewName        deviceName        propName          propValue)
  (layout          M2_M1c            defaultVia        t)
  (layout          M3_M2c            defaultVia        t)
  (layout          M4_M3c            defaultVia        t)
  (layout          M5_M4c            defaultVia        t)
  (layout          M6_M5c            defaultVia        t)

 ) ; tfcDefineDeviceProp

 symPinDevice(
 ; (name maskable layer1 purpose1  w1  layer2 purpose2   w2 legalRegion)
   (po_T  t        POLY   drawing  0.18  _NA_   _NA_     _NA_  _NA_)
   (m1_T  t        MET1   drawing  0.23  _NA_   _NA_     _NA_  _NA_)
   (m2_T  t        MET2   drawing  0.28  _NA_   _NA_     _NA_  _NA_)
   (m3_T  t        MET3   drawing  0.28  _NA_   _NA_     _NA_  _NA_)
   (m4_T  t        MET4   drawing  0.28  _NA_   _NA_     _NA_  _NA_)
   (m5_T  t        MET5   drawing  0.28  _NA_   _NA_     _NA_  _NA_)
   (m6_T  t        MET6   drawing  0.44  _NA_   _NA_     _NA_  _NA_)

 ) ; symPinDevice

) ; devices


;********************************
; COMPACTOR RULES
;********************************
compactorRules(

 compactorLayers(
  ;( layer                     usage          )
  ;( -----                     -----          )
   ( MET6                      "conductor"    )
   ( VIA5                      "via"          )
   ( MET5                      "conductor"    )
   ( VIA4                      "via"          )
   ( MET4                      "conductor"    )
   ( VIA3                      "via"          )
   ( MET3                      "conductor"    )
   ( VIA2                      "via"          )
   ( MET2                      "conductor"    )
   ( VIA1                      "via"          )
   ( MET1                      "conductor"    )
   ( CONT                      "via"          )
   ( POLY                      "conductor"    )
   ( DIFF                      "diffusion"    )
   ( PIMP                      "implant"      )
   ( NIMP                      "implant"      )
   ( NWELL                     "well"         )
   ( PWELL                     "well"         )
   ( hardFence                 "hardfence"    )
   ( softFence                 "softfence"    )
   ( prBoundary                "cellBoundary" )
 ) ;compactorLayers

) ;compactorRules


;********************************
; LX RULES
;********************************
lxRules(

 lxExtractLayers(
; ( list of layers or layer/purpose pairs  )
; ( -------------------------------------  )
  ( NWELL PWELL DBL SDNW SDPW DNW
     NIMP PIMP DIFF 
     POLY
     CONT MET1
     VIA1 MET2
     VIA2 MET3
     VIA3 MET4
     VIA4 MET5
     VIA5 MET6
  )
 ) ;lxExtractLayers

 lxNoOverlapLayers(
; ( forbidden overlaps in LX   )
; ( ------------------------   )
  ( POLY            DIFF         )
  ( POLY            NIMP         )
  ( POLY            PIMP         )
 ) ;lxNoOverlapLayers

  lxMPPTemplates(
 ; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
 ;
 ;  masterPath:
 ;  (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
 ;  [connectivity])
 ;
 ;  offsetSubpaths:
 ;  (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
 ;  [connectivity])
 ;
 ;  encSubPaths:
 ;  (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
 ;  [connectivity])
 ;
 ;  subRects:
 ;  (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap]
 ;  [connectivity] [beginSegOffset] [endSegOffset])
 ;
 ;  connectivity:
 ;  ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
 ;   [layer] [justification] [font] [textOptions] [orientation]
 ;   [refHandle] [offset])
 ;
 ; ( --------------------------------------------------------------------- )
;   (PRing
;     (("PIMP" "drawing")        0.44     nil)
;     ((("MET1" "drawing")        0.23     t       nil     nil     0.0     0.0)
;      (("PWELL" "drawing")      0.86     nil     nil     nil     0.21     0.21)
;     )
;     nil
;     ((("CONT" "drawing")        0.22     0.22     t       nil     nil     0.25     -0.2   -0.2)
;     )
;   )
;   (WellRing
;    (("NIMP" "drawing")        0.44     nil)
;    ((("MET1" "drawing")        0.23     t       nil     nil     0.0     0.0)
;     (("NWELL" "drawing")      0.86     nil     nil     nil     0.21     0.21)
;    )
;    nil
;    ((("CONT" "drawing")        0.22     0.22     t       nil     nil     0.25     -0.2   -0.2)
;    )
;   )
  ) ;lxMPPTemplates

) ; lxRules

;********************************
; P&R RULES
;********************************
prRules(

 prRoutingLayers(
 ;( layer                       preferredDirection  )
 ;( -----                       ------------------  )
  ( MET1                        "horizontal" )
  ( MET2                        "vertical" )
  ( MET3                        "horizontal" )
  ( MET4                        "vertical" )
  ( MET5                        "horizontal" )
  ( MET6                        "vertical" )
 ) ; prRoutingLayers

 prViaTypes(
 ;( device viewName             viaType    )
 ;( ---------------             -------    )
  ( ("M1_POLYc" "layout")      "default"  )
  ( ("M2_M1c" "layout")        "default"  )
  ( ("M3_M2c" "layout")        "default"  )
  ( ("M4_M3c" "layout")        "default"  )
  ( ("M5_M4c" "layout")        "default"  )
  ( ("M6_M5c" "layout")        "default"  )
 ) ;prViaTypes

 prRoutingPitch(
 ;( layer                pitch )
 ;( -----                ----- )
  ( "MET1"         0.46 )
  ( "MET2"         0.56 )
  ( "MET3"         0.56 )
  ( "MET4"         0.56 )
  ( "MET5"         0.56 )
  ( "MET6"         0.9 )
 ) ;prRoutingPitch

 prRoutingOffset(
 ;( layer                offset )
 ;( -----                ------ )
  ( MET1                 0.23 )
  ( MET2                 0.28 )
  ( MET3                 0.28 )
  ( MET4                 0.28 )
  ( MET5                 0.28 )
  ( MET6                 0.45 )
 ) ;prRoutingOffset

 prMastersliceLayers(
 ;( layers : listed in order of lowest (closest to substrate) to highest )
 ;( -------------------------------------------------------------------- )
  ( POLY       )
 ) ;prMastersliceLayers

 prOverlapLayer(
 ;( list of layers or layer/purpose pairs )
 ;( ------------------------------------- )
  ( OVERLAP )
 ) ;prOverlapLayer

 prStackVias(
 ;( viaLayerPairList    stackable )
 ;( ----------------    --------- )
  ( MET1        MET1 )
  ( MET2        MET2 )
  ( MET3        MET3 )
  ( MET4        MET4 )
  ( MET5        MET5 )
  ( MET6        MET6 )
  ( VIA1        VIA2 )
  ( VIA2        VIA3 )
  ( VIA3        VIA4 )
  ( VIA4        VIA5 )
 ) ;prStackVias

 prGenViaRules(
 ;( ViaRuleName         viaLayer     (lowerPt upperPt xPitch yPitch resistence)
 ;    Layer1            Direction|(overhang1 overhang2)    (wMin wMax overHang metalOverHang)
 ;    Layer2            Direction|(overhang1 overhang2)    (wMin wMax overHang metalOverHang)
 ;    (properties)
 ;)
 ;( ---------------------------------------------------------------------- )
  ( VIA1Array           "VIA1"  ( 0.26 0.26 0.52 0.52 5.0 )
      MET1              "horizontal"    ( 0.23 10.0 0.0 0.0 )
      MET2              "vertical"      ( 0.28 10.0 0.0 0.0 )
  )
  ( VIA2Array           "VIA2"  ( 0.26 0.26 0.52 0.52 5.0 )
      MET2              "vertical"      ( 0.28 10.0 0.0 0.0 )
      MET3              "horizontal"    ( 0.28 10.0 0.0 0.0 )
  )
  ( VIA3Array           "VIA3"  ( 0.26 0.26 0.52 0.52 5.0 )
      MET3              "vertical"      ( 0.28 10.0 0.0 0.0 )
      MET4              "horizontal"    ( 0.28 10.0 0.0 0.0 )
  )
  ( VIA4Array           "VIA4"  ( 0.26 0.26 0.52 0.52 5.0 )
      MET4              "vertical"      ( 0.28 10.0 0.0 0.0 )
      MET5              "horizontal"    ( 0.28 10.0 0.0 0.0 )
  )
  ( VIA5Array           "VIA5"  ( 0.36 0.36 0.71 0.71 3.5 )
      MET5              "vertical"      ( 0.28 10.0 0.0 0.0 )
      MET6              "horizontal"    ( 0.44 10.0 0.0 0.0 )
  )
  ( TURNM1              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET1              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET1              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
  ( TURNM2              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET2              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET2              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
  ( TURNM3              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET3              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET3              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
  ( TURNM4              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET4              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET4              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
  ( TURNM5              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET5              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET5              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
  ( TURNM6              nil     ( _NA_ _NA_ _NA_ _NA_ _NA_ )
      MET6              "vertical"      ( _NA_ _NA_ _NA_ _NA_ )
      MET6              "horizontal"    ( _NA_ _NA_ _NA_ _NA_ )
  )
 ) ;prGenViaRules

) ; prRules

//
// MultiPartPath rules
//
MPP NGRing LAYER nwell  drawing WIDTH 0.78 BEGEXT 0.39 ENDEXT 0.39 ;
MPP NGRing LAYER od     drawing WIDTH 0.30 BEGEXT 0.15 ENDEXT 0.15 ;
MPP NGRing LAYER nimp   drawing WIDTH 0.66 BEGEXT 0.33 ENDEXT 0.33 ;
MPP NGRing LAYER cont   drawing WIDTH 0.16 BEGEXT -0.08 ENDEXT -0.08 SPACE 0.18 LENGTH 0.16 ;
MPP NGRing LAYER metal1 drawing WIDTH 0.26 BEGEXT 0.13 ENDEXT 0.13 ;
//
MPP PGRing LAYER od     drawing WIDTH 0.30 BEGEXT 0.15 ENDEXT 0.15 ;
MPP PGRing LAYER pimp   drawing WIDTH 0.66 BEGEXT 0.33 ENDEXT 0.33 ;
MPP PGRing LAYER cont   drawing WIDTH 0.16 BEGEXT -0.08 ENDEXT -0.08 SPACE 0.18 LENGTH 0.16 ;
MPP PGRing LAYER metal1 drawing WIDTH 0.26 BEGEXT 0.13 ENDEXT 0.13 ;
//